### ISSUE TITLE
Exponent formatting

### ISSUE THREAD

**Issue by dfcreative** [JsCommunity/human-format#12]
Hi @JsCommunity!

Awesome util, solves many tacky nuances. I am thinking to use it in [plot-grid](https://github.com/dfcreative/plot-grid).

Though there is one thought related to this. As far as the util tries to represent values in human-oriented format, would it make sense to display exponent part as ten to the power?

E.g. `10e+20` → `10²⁰`, or `7.2973525664e-3` → `7.297 352 5664×10⁻³`? Wikipedia does so, and that is what I’ve been taught in school :)

Or is it better to delegate to a separate package?

Thanks!

**Comment by dfcreative** [comment]
FYI there is [pretty-number](https://github.com/dfcreative/pretty-number), making part of the dirty job. Mb we just have to come up with a way to run both packages.

**Comment by julien-f** [comment]
Hi @dfcreative, happy to know it's useful :)

Why do you need this? It's mainly the job of prefixes to express the size of the value.
Another thing is that I like the fact that human-format can parse what it has formatted and doing what you're suggesting would prevent or complicate this.

Anyway I'm reluctant to add a dependency to this module, if you really need this, you can do:

```js
const { value, prefix } = humanFormat.raw(1337)
console.log(`${prettyNumber(value)} ${prefix}`)
```

**Comment by dfcreative** [comment]
agreed
