### ISSUE TITLE
How to handle negative numbers?

### ISSUE THREAD

**Issue by datanotion** [JsCommunity/human-format#23]
Trying to format a negative number, even as simple as -5000 fails:

![image](https://user-images.githubusercontent.com/4722782/34754486-59131150-f57b-11e7-858c-e4d7c22fba1d.png)

Is there a certain way to handle this?

**Comment by julien-f** [comment]
Negative numbers are not currently supported, let me see what I can do :)

**Comment by julien-f** [comment]
Released as 0.10.

**Comment by datanotion** [comment]
Holy buckets batman that was FAST!  Thank you so much, I'll pull it and give it a whirl.  Appreciate the time you give to the community - its a thankless job sometimes.

**Comment by julien-f** [comment]
No problem, this was pretty easy 😃

Thank you anyway.
